import { Rol } from './rol.interface';
import { Entidad } from './entidad.interface';

export interface Usuario {
    id: number;
    authUid?: string;
    nombre: string;
    ci: string;
    email?: string;
    telefono?: string;
    rolId?: number;
    entidadId?: number;
    tipoParticipante: number;
    tipoParticipanteId?: number | null;
    primerNombre?: string;
    segundoNombre?: string;
    primerApellido?: string;
    segundoApellido?: string;
    celular?: string;
    convencional?: string;
    genero?: string;
    generoId?: number | null;
    etnia?: string;
    etniaId?: number | null;
    nacionalidadId?: number | null;
    nacionalidad?: any;
    fechaNacimiento?: string;
    provinciaId?: number | null;
    cantonId?: number | null;
    cantonReside?: string;
    parroquiaReside?: string;
    firmaUrl?: string;
    fotoPerfilUrl?: string;
    createdAt?: string;
    updatedAt?: string;
    rol?: Rol;
    entidad?: Entidad;
    autoridad?: any;
    funcionarioGad?: any;
    institucion?: any;
    estado?: number;
}
