-- AlterTable Provincias
ALTER TABLE "provincias" ADD COLUMN IF NOT EXISTS "codigo" VARCHAR(50);
ALTER TABLE "provincias" ADD COLUMN IF NOT EXISTS "estado" BOOLEAN DEFAULT true;
ALTER TABLE "provincias" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "provincias" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable Cantones
ALTER TABLE "cantones" ADD COLUMN IF NOT EXISTS "codigo" VARCHAR(50);
ALTER TABLE "cantones" ADD COLUMN IF NOT EXISTS "estado" BOOLEAN DEFAULT true;
ALTER TABLE "cantones" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "cantones" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable Parroquias
ALTER TABLE "parroquias" ADD COLUMN IF NOT EXISTS "codigo" VARCHAR(50);
ALTER TABLE "parroquias" ADD COLUMN IF NOT EXISTS "estado" BOOLEAN DEFAULT true;
ALTER TABLE "parroquias" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "parroquias" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "provincias_codigo_key" ON "provincias"("codigo");
CREATE UNIQUE INDEX IF NOT EXISTS "cantones_codigo_key" ON "cantones"("codigo");
CREATE UNIQUE INDEX IF NOT EXISTS "parroquias_codigo_key" ON "parroquias"("codigo");
